language: python
python:
  - "3.8"
env:
  - BADWORDSPATH="" TINYDB_PATH="tests/data/"
install:
  - pip install -r requirements.txt
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src/twitter_bot"
# command to run tests
script:
  - python3 setup.py
  - python3 tests/mongo_models_tests.py
  - python3 tests/db_controller_tests.py
  - python3 tests/categorization_tests.py