language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/src"
# command to run tests
script:
  - python3 tests/mongo_models_tests.py
  - python3 tests/db_controller_tests.py